export enum ActionTypes {
  ADD_EMAIL_FORM = "ADD_EMAIL_FORM",
  ADD_SIGNUP_DATA = "ADD_SIGNUP_DATA",
  ADD_FORM2_DATA = "ADD_FORM2_DATA",
  ADD_DETAIL_FORM = "ADD_DETAIL_FORM",
  ADD_CREDIT_CARD_DETAIL = "ADD_CREDIT_CARD_DETAIL",
  ADD_ADDRESS = "ADD_ADDRESS",
}
